name: Build and Deploy To Itch.io

on: push

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write  
    # This stops builds that are in-progress once a new commit comes in
    concurrency: 
      group: unity-build
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          #- StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      # Cache
      - name: Restore Library Cache
        run: |
              if [ -d "/mnt/build_cache/ld57/Library-${{ matrix.targetPlatform }}" ]; then
                echo "Restoring Library cache..."
                cp -r /mnt/build_cache/ld57/Library-${{ matrix.targetPlatform }} Library
              else
                echo "No Library cache found. A fresh build will be performed."
              fi
      - uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_BUILD_METHOD: UnityEditor.BuildPipeline.BuildPlayer
          UNITY_BUILD_EXTRA_ARGS: "-nographics -batchmode"
        with:
          runAsHostUser: true
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Store Library Cache
        run: |
              echo "Saving Library cache..."
              mkdir -p /mnt/build_cache/ld57
              rm -rf /mnt/build_cache/ld57/Library-${{ matrix.targetPlatform }}
              cp -r Library /mnt/build_cache/ld57/Library-${{ matrix.targetPlatform }}
          
  deploy:
    name: Butler Push to Itch
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write  
    needs: buildForAllSupportedPlatforms
    steps:  
      - uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL
      # Upload to Itch
      - name: Butler Push
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: ld57
          ITCH_USER: noagard
          PACKAGE: build/WebGL
      - name: Cleanup to avoid storage limit
        if: always()
        uses: geekyeggo/delete-artifact@v4
        with:
            name: Build-WebGL
